version: '2'

volumes:
  settings:                          # Only required if using PERSISTENT flag (see below)
  profiles:                          # Only required if using PERSISTENT flag (see below)

services:

  browser:
    image: bh.cr/balenalabs/browser-aarch64
    restart: unless-stopped
    privileged: true # required for UDEV to find plugged in peripherals such as a USB mouse
    network_mode: bridge
    ports:
        - '5011:5011' # management API (optional)
        - '35173:35173' # Chromium debugging port (optional)
    volumes:
      - 'settings:/data' # Only required if using PERSISTENT flag (see below)
    environment:
      KIOSK: 1
      PERSISTENT: 1
      SHOW_CURSOR: 0
      LAUNCH_URL: http://192.168.86.32:1880/ui/
      # DISPLAY_NUM: 2
  rhasspy:
    image: "rhasspy/rhasspy"
    container_name: rhasspy
    restart: unless-stopped
    volumes:
       - 'profiles:/profiles'
      #  - "/etc/localtime:/etc/localtime:ro"
    ports:
        - "12101:12101"
    devices:
        - "/dev/snd:/dev/snd"
    command: --user-profiles /profiles --profile en
    privileged: true